# Generated by Django 5.0.6 on 2024-10-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
